---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivial-go-web-app
  template:
    metadata:
      labels:
        app: trivial-go-web-app
    spec:
      containers:
      - name: webserver-simple
        image: docker.io/kostiscodefresh/gitops-simple-app:v1.0
        ports:
        - containerPort: 8080
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c', "echo "hello world" "]
      - name: init-mydb
        image: busybox:1.28
        command: ['sh', '-c', "ls -lrt"]
